version: 1
runtime: python27
api_version: 1
threadsafe: true

env_variables:
    EXPIRE_SNIPPETS: False
    EXPIRATION_TIME_IN_DAYS: 31
    MAX_BYTES_PER_SNIPPET: 1048576
    ALLOW_UUID_OVERRIDE: True
    READS_PER_MINUTE: 60
    WRITES_PER_MINUTE: 10
    LISTS_PER_MINUTE: 10

handlers:

- url: /tasks/.*
  script: tasks.application
  login: admin

- url: /.*
  script: main.application
  secure: always

libraries:

- name: webapp2
  version: latest
